import 'package:flutter/material.dart';
import 'package:conduit_vt/conduit_vt.dart';

enum AppPalette {
  catppuccin,
  tokyoNight,
  dracula,
  nord,
  gruvbox,
  solarized,
  oneDark,
  rosePine,
  everforest,
  monokai,
  ayuDark,
  kanagawa,
  nightOwl,
  palenight,
  synthwave,
  githubDark,
}

extension AppPaletteDetails on AppPalette {
  String get label => switch (this) {
    AppPalette.catppuccin => 'Catppuccin',
    AppPalette.tokyoNight => 'Tokyo Night',
    AppPalette.dracula => 'Dracula',
    AppPalette.nord => 'Nord',
    AppPalette.gruvbox => 'Gruvbox',
    AppPalette.solarized => 'Solarized',
    AppPalette.oneDark => 'One Dark',
    AppPalette.rosePine => 'Rosé Pine',
    AppPalette.everforest => 'Everforest',
    AppPalette.monokai => 'Monokai',
    AppPalette.ayuDark => 'Ayu Dark',
    AppPalette.kanagawa => 'Kanagawa',
    AppPalette.nightOwl => 'Night Owl',
    AppPalette.palenight => 'Palenight',
    AppPalette.synthwave => 'Synthwave',
    AppPalette.githubDark => 'GitHub Dark',
  };

  String get caption => switch (this) {
    AppPalette.catppuccin => 'Mocha, calm and polished',
    AppPalette.tokyoNight => 'Deep blue IDE focus',
    AppPalette.dracula => 'High-contrast neon classic',
    AppPalette.nord => 'Arctic, restrained, cool',
    AppPalette.gruvbox => 'Warm retro terminal energy',
    AppPalette.solarized => 'Balanced low-glare contrast',
    AppPalette.oneDark => 'Atom-inspired editor calm',
    AppPalette.rosePine => 'Muted dusk, soft contrast',
    AppPalette.everforest => 'Green low-glare woodland',
    AppPalette.monokai => 'Punchy classic code color',
    AppPalette.ayuDark => 'Warm amber night coding',
    AppPalette.kanagawa => 'Muted ink and wave tones',
    AppPalette.nightOwl => 'Crisp blue late-night focus',
    AppPalette.palenight => 'Soft violet editor glow',
    AppPalette.synthwave => 'Electric retro terminal pop',
    AppPalette.githubDark => 'Quiet modern code contrast',
  };

  Color get seed => accent;

  Color get accent => switch (this) {
    AppPalette.catppuccin => const Color(0xFFCBA6F7),
    AppPalette.tokyoNight => const Color(0xFF7AA2F7),
    AppPalette.dracula => const Color(0xFFBD93F9),
    AppPalette.nord => const Color(0xFF88C0D0),
    AppPalette.gruvbox => const Color(0xFFD79921),
    AppPalette.solarized => const Color(0xFF268BD2),
    AppPalette.oneDark => const Color(0xFF61AFEF),
    AppPalette.rosePine => const Color(0xFFC4A7E7),
    AppPalette.everforest => const Color(0xFFA7C080),
    AppPalette.monokai => const Color(0xFFA6E22E),
    AppPalette.ayuDark => const Color(0xFFFFB454),
    AppPalette.kanagawa => const Color(0xFF7E9CD8),
    AppPalette.nightOwl => const Color(0xFF82AAFF),
    AppPalette.palenight => const Color(0xFFC792EA),
    AppPalette.synthwave => const Color(0xFFFF7EDB),
    AppPalette.githubDark => const Color(0xFF58A6FF),
  };

  Color get accentSecondary => switch (this) {
    AppPalette.catppuccin => const Color(0xFFF5C2E7),
    AppPalette.tokyoNight => const Color(0xFFBB9AF7),
    AppPalette.dracula => const Color(0xFFFF79C6),
    AppPalette.nord => const Color(0xFF81A1C1),
    AppPalette.gruvbox => const Color(0xFFB16286),
    AppPalette.solarized => const Color(0xFFD33682),
    AppPalette.oneDark => const Color(0xFFC678DD),
    AppPalette.rosePine => const Color(0xFFEBBCBA),
    AppPalette.everforest => const Color(0xFFE67E80),
    AppPalette.monokai => const Color(0xFFF92672),
    AppPalette.ayuDark => const Color(0xFFFF8F40),
    AppPalette.kanagawa => const Color(0xFFC8C093),
    AppPalette.nightOwl => const Color(0xFFC792EA),
    AppPalette.palenight => const Color(0xFF89DDFF),
    AppPalette.synthwave => const Color(0xFF36F9F6),
    AppPalette.githubDark => const Color(0xFFBC8CFF),
  };

  Color get canvas => switch (this) {
    AppPalette.catppuccin => const Color(0xFF0F0F18),
    AppPalette.tokyoNight => const Color(0xFF0A0E1A),
    AppPalette.dracula => const Color(0xFF15161E),
    AppPalette.nord => const Color(0xFF1E222B),
    AppPalette.gruvbox => const Color(0xFF1A1B1B),
    AppPalette.solarized => const Color(0xFF002731),
    AppPalette.oneDark => const Color(0xFF181A20),
    AppPalette.rosePine => const Color(0xFF191724),
    AppPalette.everforest => const Color(0xFF1E2326),
    AppPalette.monokai => const Color(0xFF1B1C1A),
    AppPalette.ayuDark => const Color(0xFF0B0E14),
    AppPalette.kanagawa => const Color(0xFF16161D),
    AppPalette.nightOwl => const Color(0xFF011627),
    AppPalette.palenight => const Color(0xFF202331),
    AppPalette.synthwave => const Color(0xFF191528),
    AppPalette.githubDark => const Color(0xFF0D1117),
  };

  Color get panel => switch (this) {
    AppPalette.catppuccin => const Color(0xFF181825),
    AppPalette.tokyoNight => const Color(0xFF131826),
    AppPalette.dracula => const Color(0xFF1F2029),
    AppPalette.nord => const Color(0xFF272C36),
    AppPalette.gruvbox => const Color(0xFF24262A),
    AppPalette.solarized => const Color(0xFF073642),
    AppPalette.oneDark => const Color(0xFF21252B),
    AppPalette.rosePine => const Color(0xFF1F1D2E),
    AppPalette.everforest => const Color(0xFF272E33),
    AppPalette.monokai => const Color(0xFF272822),
    AppPalette.ayuDark => const Color(0xFF11151C),
    AppPalette.kanagawa => const Color(0xFF1F1F28),
    AppPalette.nightOwl => const Color(0xFF071D2F),
    AppPalette.palenight => const Color(0xFF292D3E),
    AppPalette.synthwave => const Color(0xFF241B3D),
    AppPalette.githubDark => const Color(0xFF161B22),
  };

  Color get panelElevated => switch (this) {
    AppPalette.catppuccin => const Color(0xFF1E1E2E),
    AppPalette.tokyoNight => const Color(0xFF1A2138),
    AppPalette.dracula => const Color(0xFF282A36),
    AppPalette.nord => const Color(0xFF2E3440),
    AppPalette.gruvbox => const Color(0xFF2C2F33),
    AppPalette.solarized => const Color(0xFF0B3D49),
    AppPalette.oneDark => const Color(0xFF282C34),
    AppPalette.rosePine => const Color(0xFF26233A),
    AppPalette.everforest => const Color(0xFF2E383C),
    AppPalette.monokai => const Color(0xFF2D2E29),
    AppPalette.ayuDark => const Color(0xFF191E2A),
    AppPalette.kanagawa => const Color(0xFF252535),
    AppPalette.nightOwl => const Color(0xFF0B2942),
    AppPalette.palenight => const Color(0xFF34394F),
    AppPalette.synthwave => const Color(0xFF2D2350),
    AppPalette.githubDark => const Color(0xFF21262D),
  };

  Color get hairline => switch (this) {
    AppPalette.catppuccin => const Color(0xFF26273A),
    AppPalette.tokyoNight => const Color(0xFF1F2945),
    AppPalette.dracula => const Color(0xFF353746),
    AppPalette.nord => const Color(0xFF3B4252),
    AppPalette.gruvbox => const Color(0xFF332F2C),
    AppPalette.solarized => const Color(0xFF124854),
    AppPalette.oneDark => const Color(0xFF353B45),
    AppPalette.rosePine => const Color(0xFF403D52),
    AppPalette.everforest => const Color(0xFF3A464C),
    AppPalette.monokai => const Color(0xFF3A3B35),
    AppPalette.ayuDark => const Color(0xFF242C3A),
    AppPalette.kanagawa => const Color(0xFF363646),
    AppPalette.nightOwl => const Color(0xFF12344D),
    AppPalette.palenight => const Color(0xFF3D435E),
    AppPalette.synthwave => const Color(0xFF3B2D67),
    AppPalette.githubDark => const Color(0xFF30363D),
  };

  Color get border => switch (this) {
    AppPalette.catppuccin => const Color(0xFF313244),
    AppPalette.tokyoNight => const Color(0xFF2C3858),
    AppPalette.dracula => const Color(0xFF44475A),
    AppPalette.nord => const Color(0xFF434C5E),
    AppPalette.gruvbox => const Color(0xFF3C3836),
    AppPalette.solarized => const Color(0xFF195563),
    AppPalette.oneDark => const Color(0xFF3E4451),
    AppPalette.rosePine => const Color(0xFF524F67),
    AppPalette.everforest => const Color(0xFF4F5B58),
    AppPalette.monokai => const Color(0xFF49483E),
    AppPalette.ayuDark => const Color(0xFF334155),
    AppPalette.kanagawa => const Color(0xFF54546D),
    AppPalette.nightOwl => const Color(0xFF1D4A66),
    AppPalette.palenight => const Color(0xFF4B5274),
    AppPalette.synthwave => const Color(0xFF4A3A7A),
    AppPalette.githubDark => const Color(0xFF3B434D),
  };

  Color get foreground => switch (this) {
    AppPalette.catppuccin => const Color(0xFFCDD6F4),
    AppPalette.tokyoNight => const Color(0xFFC0CAF5),
    AppPalette.dracula => const Color(0xFFF8F8F2),
    AppPalette.nord => const Color(0xFFE5E9F0),
    AppPalette.gruvbox => const Color(0xFFEBDBB2),
    AppPalette.solarized => const Color(0xFFEEE8D5),
    AppPalette.oneDark => const Color(0xFFABB2BF),
    AppPalette.rosePine => const Color(0xFFE0DEF4),
    AppPalette.everforest => const Color(0xFFD3C6AA),
    AppPalette.monokai => const Color(0xFFF8F8F2),
    AppPalette.ayuDark => const Color(0xFFB3B1AD),
    AppPalette.kanagawa => const Color(0xFFDCD7BA),
    AppPalette.nightOwl => const Color(0xFFD6DEEB),
    AppPalette.palenight => const Color(0xFFA6ACCD),
    AppPalette.synthwave => const Color(0xFFF4F4F7),
    AppPalette.githubDark => const Color(0xFFC9D1D9),
  };

  Color get mutedForeground => switch (this) {
    AppPalette.catppuccin => const Color(0xFF9399B2),
    AppPalette.tokyoNight => const Color(0xFF7E89B5),
    AppPalette.dracula => const Color(0xFF9A9CB0),
    AppPalette.nord => const Color(0xFFA8B0BF),
    AppPalette.gruvbox => const Color(0xFFA89984),
    AppPalette.solarized => const Color(0xFF93A1A1),
    AppPalette.oneDark => const Color(0xFF828997),
    AppPalette.rosePine => const Color(0xFF908CAA),
    AppPalette.everforest => const Color(0xFF9DA9A0),
    AppPalette.monokai => const Color(0xFFCFCFC2),
    AppPalette.ayuDark => const Color(0xFF828C99),
    AppPalette.kanagawa => const Color(0xFF9CABCA),
    AppPalette.nightOwl => const Color(0xFF7E9DB5),
    AppPalette.palenight => const Color(0xFF828BB8),
    AppPalette.synthwave => const Color(0xFFC9B7FF),
    AppPalette.githubDark => const Color(0xFF8B949E),
  };

  Color get subtleForeground => switch (this) {
    AppPalette.catppuccin => const Color(0xFF6C7086),
    AppPalette.tokyoNight => const Color(0xFF565F89),
    AppPalette.dracula => const Color(0xFF6272A4),
    AppPalette.nord => const Color(0xFF4C566A),
    AppPalette.gruvbox => const Color(0xFF7C6F64),
    AppPalette.solarized => const Color(0xFF586E75),
    AppPalette.oneDark => const Color(0xFF5C6370),
    AppPalette.rosePine => const Color(0xFF6E6A86),
    AppPalette.everforest => const Color(0xFF859289),
    AppPalette.monokai => const Color(0xFF75715E),
    AppPalette.ayuDark => const Color(0xFF5C6773),
    AppPalette.kanagawa => const Color(0xFF727169),
    AppPalette.nightOwl => const Color(0xFF637E99),
    AppPalette.palenight => const Color(0xFF676E95),
    AppPalette.synthwave => const Color(0xFF8B7EC8),
    AppPalette.githubDark => const Color(0xFF6E7681),
  };

  Color get success => switch (this) {
    AppPalette.catppuccin => const Color(0xFFA6E3A1),
    AppPalette.tokyoNight => const Color(0xFF9ECE6A),
    AppPalette.dracula => const Color(0xFF50FA7B),
    AppPalette.nord => const Color(0xFFA3BE8C),
    AppPalette.gruvbox => const Color(0xFFB8BB26),
    AppPalette.solarized => const Color(0xFF859900),
    AppPalette.oneDark => const Color(0xFF98C379),
    AppPalette.rosePine => const Color(0xFF9CCFD8),
    AppPalette.everforest => const Color(0xFFA7C080),
    AppPalette.monokai => const Color(0xFFA6E22E),
    AppPalette.ayuDark => const Color(0xFFC2D94C),
    AppPalette.kanagawa => const Color(0xFF98BB6C),
    AppPalette.nightOwl => const Color(0xFF22DA6E),
    AppPalette.palenight => const Color(0xFFC3E88D),
    AppPalette.synthwave => const Color(0xFF72F1B8),
    AppPalette.githubDark => const Color(0xFF3FB950),
  };

  Color get warning => switch (this) {
    AppPalette.catppuccin => const Color(0xFFF9E2AF),
    AppPalette.tokyoNight => const Color(0xFFE0AF68),
    AppPalette.dracula => const Color(0xFFF1FA8C),
    AppPalette.nord => const Color(0xFFEBCB8B),
    AppPalette.gruvbox => const Color(0xFFFABD2F),
    AppPalette.solarized => const Color(0xFFB58900),
    AppPalette.oneDark => const Color(0xFFE5C07B),
    AppPalette.rosePine => const Color(0xFFF6C177),
    AppPalette.everforest => const Color(0xFFDBBC7F),
    AppPalette.monokai => const Color(0xFFE6DB74),
    AppPalette.ayuDark => const Color(0xFFFFB454),
    AppPalette.kanagawa => const Color(0xFFE6C384),
    AppPalette.nightOwl => const Color(0xFFFFEB95),
    AppPalette.palenight => const Color(0xFFFFCB6B),
    AppPalette.synthwave => const Color(0xFFFFD866),
    AppPalette.githubDark => const Color(0xFFD29922),
  };

  Color get danger => switch (this) {
    AppPalette.catppuccin => const Color(0xFFF38BA8),
    AppPalette.tokyoNight => const Color(0xFFF7768E),
    AppPalette.dracula => const Color(0xFFFF5555),
    AppPalette.nord => const Color(0xFFBF616A),
    AppPalette.gruvbox => const Color(0xFFFB4934),
    AppPalette.solarized => const Color(0xFFDC322F),
    AppPalette.oneDark => const Color(0xFFE06C75),
    AppPalette.rosePine => const Color(0xFFEB6F92),
    AppPalette.everforest => const Color(0xFFE67E80),
    AppPalette.monokai => const Color(0xFFF92672),
    AppPalette.ayuDark => const Color(0xFFFF3333),
    AppPalette.kanagawa => const Color(0xFFC34043),
    AppPalette.nightOwl => const Color(0xFFEF5350),
    AppPalette.palenight => const Color(0xFFF07178),
    AppPalette.synthwave => const Color(0xFFFF5370),
    AppPalette.githubDark => const Color(0xFFF85149),
  };

  Color get accentSoft => accent.withValues(alpha: 0.16);
  Color get accentGlow => accent.withValues(alpha: 0.08);
  Color get accentOnDark => Color.lerp(accent, Colors.black, 0.55)!;

  Color get canvasLight => switch (this) {
    AppPalette.catppuccin => const Color(0xFFEFF1F5),
    AppPalette.tokyoNight => const Color(0xFFE9ECF5),
    AppPalette.dracula => const Color(0xFFF7F7F4),
    AppPalette.nord => const Color(0xFFECEFF4),
    AppPalette.gruvbox => const Color(0xFFFBF1C7),
    AppPalette.solarized => const Color(0xFFFDF6E3),
    AppPalette.oneDark => const Color(0xFFECEFF4),
    AppPalette.rosePine => const Color(0xFFFFFAF3),
    AppPalette.everforest => const Color(0xFFFDF6E3),
    AppPalette.monokai => const Color(0xFFF7F7EF),
    AppPalette.ayuDark => const Color(0xFFFFF8E7),
    AppPalette.kanagawa => const Color(0xFFF2ECBC),
    AppPalette.nightOwl => const Color(0xFFEAF4FF),
    AppPalette.palenight => const Color(0xFFF2F0FF),
    AppPalette.synthwave => const Color(0xFFFFF0FB),
    AppPalette.githubDark => const Color(0xFFF0F3F6),
  };

  Color get panelLight => Color.lerp(canvasLight, Colors.white, 0.55)!;
  Color get panelElevatedLight => Colors.white;
  Color get hairlineLight => Color.lerp(canvasLight, accent, 0.06)!;
  Color get borderLight => Color.lerp(canvasLight, accent, 0.16)!;
  Color get foregroundLight => switch (this) {
    AppPalette.catppuccin => const Color(0xFF1E1E2E),
    AppPalette.tokyoNight => const Color(0xFF111A2D),
    AppPalette.dracula => const Color(0xFF1F2029),
    AppPalette.nord => const Color(0xFF2E3440),
    AppPalette.gruvbox => const Color(0xFF3C3836),
    AppPalette.solarized => const Color(0xFF073642),
    AppPalette.oneDark => const Color(0xFF282C34),
    AppPalette.rosePine => const Color(0xFF191724),
    AppPalette.everforest => const Color(0xFF3A464C),
    AppPalette.monokai => const Color(0xFF272822),
    AppPalette.ayuDark => const Color(0xFF191E2A),
    AppPalette.kanagawa => const Color(0xFF1F1F28),
    AppPalette.nightOwl => const Color(0xFF011627),
    AppPalette.palenight => const Color(0xFF292D3E),
    AppPalette.synthwave => const Color(0xFF241B3D),
    AppPalette.githubDark => const Color(0xFF24292F),
  };
  Color get mutedForegroundLight =>
      Color.lerp(foregroundLight, canvasLight, 0.35)!;
  Color get subtleForegroundLight =>
      Color.lerp(foregroundLight, canvasLight, 0.55)!;

  Color canvasFor(Brightness b) => b == Brightness.dark ? canvas : canvasLight;
  Color panelFor(Brightness b) => b == Brightness.dark ? panel : panelLight;
  Color panelElevatedFor(Brightness b) =>
      b == Brightness.dark ? panelElevated : panelElevatedLight;
  Color hairlineFor(Brightness b) =>
      b == Brightness.dark ? hairline : hairlineLight;
  Color borderFor(Brightness b) => b == Brightness.dark ? border : borderLight;
  Color foregroundFor(Brightness b) =>
      b == Brightness.dark ? foreground : foregroundLight;
  Color mutedForegroundFor(Brightness b) =>
      b == Brightness.dark ? mutedForeground : mutedForegroundLight;
  Color subtleForegroundFor(Brightness b) =>
      b == Brightness.dark ? subtleForeground : subtleForegroundLight;

  Color terminalBackgroundFor(Brightness b) => canvasFor(b);
  Color terminalPanelFor(Brightness b) => panelFor(b);
  Color terminalForegroundFor(Brightness b) => foregroundFor(b);
  Color terminalMutedForegroundFor(Brightness b) => mutedForegroundFor(b);
  Color terminalBorderFor(Brightness b) => hairlineFor(b);

  TerminalTheme terminalThemeFor(Brightness brightness) =>
      brightness == Brightness.dark ? terminalTheme : lightTerminalTheme;

  TerminalTheme get lightTerminalTheme => switch (this) {
    AppPalette.catppuccin => const TerminalTheme(
      cursor: Color(0xFF4C4F69),
      selection: Color(0x66ACB0BE),
      foreground: Color(0xFF4C4F69),
      background: Color(0xFFEFF1F5),
      black: Color(0xFF5C5F77),
      red: Color(0xFFD20F39),
      green: Color(0xFF40A02B),
      yellow: Color(0xFFDF8E1D),
      blue: Color(0xFF1E66F5),
      magenta: Color(0xFFEA76CB),
      cyan: Color(0xFF179299),
      white: Color(0xFFACB0BE),
      brightBlack: Color(0xFF6C6F85),
      brightRed: Color(0xFFD20F39),
      brightGreen: Color(0xFF40A02B),
      brightYellow: Color(0xFFDF8E1D),
      brightBlue: Color(0xFF1E66F5),
      brightMagenta: Color(0xFFEA76CB),
      brightCyan: Color(0xFF179299),
      brightWhite: Color(0xFFBCC0CC),
      searchHitBackground: Color(0xFFDF8E1D),
      searchHitBackgroundCurrent: Color(0xFF40A02B),
      searchHitForeground: Color(0xFFEFF1F5),
    ),
    AppPalette.tokyoNight => const TerminalTheme(
      cursor: Color(0xFF3760BF),
      selection: Color(0x66899AD6),
      foreground: Color(0xFF3760BF),
      background: Color(0xFFE9ECF5),
      black: Color(0xFF6172B0),
      red: Color(0xFFF52A65),
      green: Color(0xFF587539),
      yellow: Color(0xFF8C6C3E),
      blue: Color(0xFF2E7DE9),
      magenta: Color(0xFF9854F1),
      cyan: Color(0xFF007197),
      white: Color(0xFFA1A6C5),
      brightBlack: Color(0xFFA1A6C5),
      brightRed: Color(0xFFF52A65),
      brightGreen: Color(0xFF587539),
      brightYellow: Color(0xFF8C6C3E),
      brightBlue: Color(0xFF2E7DE9),
      brightMagenta: Color(0xFF9854F1),
      brightCyan: Color(0xFF007197),
      brightWhite: Color(0xFF3760BF),
      searchHitBackground: Color(0xFF8C6C3E),
      searchHitBackgroundCurrent: Color(0xFF2E7DE9),
      searchHitForeground: Color(0xFFE9ECF5),
    ),
    AppPalette.dracula => const TerminalTheme(
      cursor: Color(0xFF282A36),
      selection: Color(0x66C7C8D1),
      foreground: Color(0xFF282A36),
      background: Color(0xFFF7F7F4),
      black: Color(0xFF44475A),
      red: Color(0xFFFF5555),
      green: Color(0xFF1E9F4A),
      yellow: Color(0xFF9A7B00),
      blue: Color(0xFF6250C8),
      magenta: Color(0xFFC7448F),
      cyan: Color(0xFF087C8F),
      white: Color(0xFFD7D7D2),
      brightBlack: Color(0xFF6272A4),
      brightRed: Color(0xFFD73838),
      brightGreen: Color(0xFF188A3E),
      brightYellow: Color(0xFF806600),
      brightBlue: Color(0xFF4E3FB3),
      brightMagenta: Color(0xFFA93478),
      brightCyan: Color(0xFF066B7B),
      brightWhite: Color(0xFF282A36),
      searchHitBackground: Color(0xFFF1C40F),
      searchHitBackgroundCurrent: Color(0xFF50FA7B),
      searchHitForeground: Color(0xFF282A36),
    ),
    AppPalette.nord => const TerminalTheme(
      cursor: Color(0xFF2E3440),
      selection: Color(0x66D8DEE9),
      foreground: Color(0xFF2E3440),
      background: Color(0xFFECEFF4),
      black: Color(0xFF3B4252),
      red: Color(0xFFBF616A),
      green: Color(0xFF4F7A37),
      yellow: Color(0xFFB48B37),
      blue: Color(0xFF5E81AC),
      magenta: Color(0xFF8F5E84),
      cyan: Color(0xFF548E9B),
      white: Color(0xFFD8DEE9),
      brightBlack: Color(0xFF4C566A),
      brightRed: Color(0xFFBF616A),
      brightGreen: Color(0xFF4F7A37),
      brightYellow: Color(0xFFB48B37),
      brightBlue: Color(0xFF5E81AC),
      brightMagenta: Color(0xFF8F5E84),
      brightCyan: Color(0xFF548E9B),
      brightWhite: Color(0xFF2E3440),
      searchHitBackground: Color(0xFFEBCB8B),
      searchHitBackgroundCurrent: Color(0xFF88C0D0),
      searchHitForeground: Color(0xFF2E3440),
    ),
    AppPalette.gruvbox => const TerminalTheme(
      cursor: Color(0xFF3C3836),
      selection: Color(0x66D5C4A1),
      foreground: Color(0xFF3C3836),
      background: Color(0xFFFBF1C7),
      black: Color(0xFF7C6F64),
      red: Color(0xFFCC241D),
      green: Color(0xFF79740E),
      yellow: Color(0xFFB57614),
      blue: Color(0xFF076678),
      magenta: Color(0xFF8F3F71),
      cyan: Color(0xFF427B58),
      white: Color(0xFFD5C4A1),
      brightBlack: Color(0xFF928374),
      brightRed: Color(0xFF9D0006),
      brightGreen: Color(0xFF79740E),
      brightYellow: Color(0xFFB57614),
      brightBlue: Color(0xFF076678),
      brightMagenta: Color(0xFF8F3F71),
      brightCyan: Color(0xFF427B58),
      brightWhite: Color(0xFF3C3836),
      searchHitBackground: Color(0xFFD79921),
      searchHitBackgroundCurrent: Color(0xFF98971A),
      searchHitForeground: Color(0xFFFBF1C7),
    ),
    AppPalette.solarized => const TerminalTheme(
      cursor: Color(0xFF586E75),
      selection: Color(0x66EEE8D5),
      foreground: Color(0xFF586E75),
      background: Color(0xFFFDF6E3),
      black: Color(0xFF073642),
      red: Color(0xFFDC322F),
      green: Color(0xFF859900),
      yellow: Color(0xFFB58900),
      blue: Color(0xFF268BD2),
      magenta: Color(0xFFD33682),
      cyan: Color(0xFF2AA198),
      white: Color(0xFFEEE8D5),
      brightBlack: Color(0xFF002B36),
      brightRed: Color(0xFFCB4B16),
      brightGreen: Color(0xFF586E75),
      brightYellow: Color(0xFF657B83),
      brightBlue: Color(0xFF839496),
      brightMagenta: Color(0xFF6C71C4),
      brightCyan: Color(0xFF93A1A1),
      brightWhite: Color(0xFFFDF6E3),
      searchHitBackground: Color(0xFFB58900),
      searchHitBackgroundCurrent: Color(0xFF268BD2),
      searchHitForeground: Color(0xFFFDF6E3),
    ),
    AppPalette.oneDark => const TerminalTheme(
      cursor: Color(0xFF383A42),
      selection: Color(0x66C8CCD4),
      foreground: Color(0xFF383A42),
      background: Color(0xFFECEFF4),
      black: Color(0xFF4F5666),
      red: Color(0xFFE45649),
      green: Color(0xFF50A14F),
      yellow: Color(0xFFC18401),
      blue: Color(0xFF4078F2),
      magenta: Color(0xFFA626A4),
      cyan: Color(0xFF0184BC),
      white: Color(0xFFA0A1A7),
      brightBlack: Color(0xFF696C77),
      brightRed: Color(0xFFE45649),
      brightGreen: Color(0xFF50A14F),
      brightYellow: Color(0xFFC18401),
      brightBlue: Color(0xFF4078F2),
      brightMagenta: Color(0xFFA626A4),
      brightCyan: Color(0xFF0184BC),
      brightWhite: Color(0xFF383A42),
      searchHitBackground: Color(0xFFE5C07B),
      searchHitBackgroundCurrent: Color(0xFF61AFEF),
      searchHitForeground: Color(0xFFECEFF4),
    ),
    AppPalette.rosePine => const TerminalTheme(
      cursor: Color(0xFF575279),
      selection: Color(0x66DFDAD9),
      foreground: Color(0xFF575279),
      background: Color(0xFFFFFAF3),
      black: Color(0xFF797593),
      red: Color(0xFFB4637A),
      green: Color(0xFF286983),
      yellow: Color(0xFFEA9D34),
      blue: Color(0xFF56949F),
      magenta: Color(0xFF907AA9),
      cyan: Color(0xFFD7827E),
      white: Color(0xFFDFDAD9),
      brightBlack: Color(0xFF9893A5),
      brightRed: Color(0xFFB4637A),
      brightGreen: Color(0xFF286983),
      brightYellow: Color(0xFFEA9D34),
      brightBlue: Color(0xFF56949F),
      brightMagenta: Color(0xFF907AA9),
      brightCyan: Color(0xFFD7827E),
      brightWhite: Color(0xFF575279),
      searchHitBackground: Color(0xFFF6C177),
      searchHitBackgroundCurrent: Color(0xFFC4A7E7),
      searchHitForeground: Color(0xFFFFFAF3),
    ),
    AppPalette.everforest => const TerminalTheme(
      cursor: Color(0xFF5C6A72),
      selection: Color(0x66D8D3BA),
      foreground: Color(0xFF5C6A72),
      background: Color(0xFFFDF6E3),
      black: Color(0xFF5C6A72),
      red: Color(0xFFF85552),
      green: Color(0xFF8DA101),
      yellow: Color(0xFFDFA000),
      blue: Color(0xFF3A94C5),
      magenta: Color(0xFFDF69BA),
      cyan: Color(0xFF35A77C),
      white: Color(0xFFD8D3BA),
      brightBlack: Color(0xFF829181),
      brightRed: Color(0xFFF85552),
      brightGreen: Color(0xFF8DA101),
      brightYellow: Color(0xFFDFA000),
      brightBlue: Color(0xFF3A94C5),
      brightMagenta: Color(0xFFDF69BA),
      brightCyan: Color(0xFF35A77C),
      brightWhite: Color(0xFF5C6A72),
      searchHitBackground: Color(0xFFDBBC7F),
      searchHitBackgroundCurrent: Color(0xFFA7C080),
      searchHitForeground: Color(0xFFFDF6E3),
    ),
    AppPalette.monokai => const TerminalTheme(
      cursor: Color(0xFF272822),
      selection: Color(0x66D7D7C7),
      foreground: Color(0xFF272822),
      background: Color(0xFFF7F7EF),
      black: Color(0xFF49483E),
      red: Color(0xFFF92672),
      green: Color(0xFF669900),
      yellow: Color(0xFFC4A000),
      blue: Color(0xFF4477AA),
      magenta: Color(0xFF9E6FFE),
      cyan: Color(0xFF1F9EAA),
      white: Color(0xFFD7D7C7),
      brightBlack: Color(0xFF75715E),
      brightRed: Color(0xFFF92672),
      brightGreen: Color(0xFF669900),
      brightYellow: Color(0xFFC4A000),
      brightBlue: Color(0xFF4477AA),
      brightMagenta: Color(0xFF9E6FFE),
      brightCyan: Color(0xFF1F9EAA),
      brightWhite: Color(0xFF272822),
      searchHitBackground: Color(0xFFE6DB74),
      searchHitBackgroundCurrent: Color(0xFFA6E22E),
      searchHitForeground: Color(0xFFF7F7EF),
    ),
    AppPalette.ayuDark ||
    AppPalette.kanagawa ||
    AppPalette.nightOwl ||
    AppPalette.palenight ||
    AppPalette.synthwave ||
    AppPalette.githubDark => const TerminalTheme(
      cursor: Color(0xFF383A42),
      selection: Color(0x66C8CCD4),
      foreground: Color(0xFF383A42),
      background: Color(0xFFECEFF4),
      black: Color(0xFF4F5666),
      red: Color(0xFFE45649),
      green: Color(0xFF50A14F),
      yellow: Color(0xFFC18401),
      blue: Color(0xFF4078F2),
      magenta: Color(0xFFA626A4),
      cyan: Color(0xFF0184BC),
      white: Color(0xFFA0A1A7),
      brightBlack: Color(0xFF696C77),
      brightRed: Color(0xFFE45649),
      brightGreen: Color(0xFF50A14F),
      brightYellow: Color(0xFFC18401),
      brightBlue: Color(0xFF4078F2),
      brightMagenta: Color(0xFFA626A4),
      brightCyan: Color(0xFF0184BC),
      brightWhite: Color(0xFF383A42),
      searchHitBackground: Color(0xFFE5C07B),
      searchHitBackgroundCurrent: Color(0xFF61AFEF),
      searchHitForeground: Color(0xFFECEFF4),
    ),
  };

  TerminalTheme get terminalTheme => switch (this) {
    AppPalette.catppuccin => const TerminalTheme(
      cursor: Color(0xFFF5E0DC),
      selection: Color(0x6645475A),
      foreground: Color(0xFFCDD6F4),
      background: Color(0xFF0F0F18),
      black: Color(0xFF45475A),
      red: Color(0xFFF38BA8),
      green: Color(0xFFA6E3A1),
      yellow: Color(0xFFF9E2AF),
      blue: Color(0xFF89B4FA),
      magenta: Color(0xFFF5C2E7),
      cyan: Color(0xFF94E2D5),
      white: Color(0xFFBAC2DE),
      brightBlack: Color(0xFF585B70),
      brightRed: Color(0xFFF38BA8),
      brightGreen: Color(0xFFA6E3A1),
      brightYellow: Color(0xFFF9E2AF),
      brightBlue: Color(0xFF89B4FA),
      brightMagenta: Color(0xFFF5C2E7),
      brightCyan: Color(0xFF94E2D5),
      brightWhite: Color(0xFFA6ADC8),
      searchHitBackground: Color(0xFFF9E2AF),
      searchHitBackgroundCurrent: Color(0xFFA6E3A1),
      searchHitForeground: Color(0xFF0F0F18),
    ),
    AppPalette.tokyoNight => const TerminalTheme(
      cursor: Color(0xFFC0CAF5),
      selection: Color(0x66565F89),
      foreground: Color(0xFFC0CAF5),
      background: Color(0xFF0A0E1A),
      black: Color(0xFF15161E),
      red: Color(0xFFF7768E),
      green: Color(0xFF9ECE6A),
      yellow: Color(0xFFE0AF68),
      blue: Color(0xFF7AA2F7),
      magenta: Color(0xFFBB9AF7),
      cyan: Color(0xFF7DCFFF),
      white: Color(0xFFA9B1D6),
      brightBlack: Color(0xFF414868),
      brightRed: Color(0xFFF7768E),
      brightGreen: Color(0xFF9ECE6A),
      brightYellow: Color(0xFFE0AF68),
      brightBlue: Color(0xFF7AA2F7),
      brightMagenta: Color(0xFFBB9AF7),
      brightCyan: Color(0xFF7DCFFF),
      brightWhite: Color(0xFFC0CAF5),
      searchHitBackground: Color(0xFFE0AF68),
      searchHitBackgroundCurrent: Color(0xFF7AA2F7),
      searchHitForeground: Color(0xFF0A0E1A),
    ),
    AppPalette.dracula => const TerminalTheme(
      cursor: Color(0xFFF8F8F2),
      selection: Color(0x66565F89),
      foreground: Color(0xFFF8F8F2),
      background: Color(0xFF15161E),
      black: Color(0xFF21222C),
      red: Color(0xFFFF5555),
      green: Color(0xFF50FA7B),
      yellow: Color(0xFFF1FA8C),
      blue: Color(0xFFBD93F9),
      magenta: Color(0xFFFF79C6),
      cyan: Color(0xFF8BE9FD),
      white: Color(0xFFF8F8F2),
      brightBlack: Color(0xFF6272A4),
      brightRed: Color(0xFFFF6E6E),
      brightGreen: Color(0xFF69FF94),
      brightYellow: Color(0xFFFFFFA5),
      brightBlue: Color(0xFFD6ACFF),
      brightMagenta: Color(0xFFFF92DF),
      brightCyan: Color(0xFFA4FFFF),
      brightWhite: Color(0xFFFFFFFF),
      searchHitBackground: Color(0xFFF1FA8C),
      searchHitBackgroundCurrent: Color(0xFF50FA7B),
      searchHitForeground: Color(0xFF15161E),
    ),
    AppPalette.nord => const TerminalTheme(
      cursor: Color(0xFFD8DEE9),
      selection: Color(0x664C566A),
      foreground: Color(0xFFE5E9F0),
      background: Color(0xFF1E222B),
      black: Color(0xFF3B4252),
      red: Color(0xFFBF616A),
      green: Color(0xFFA3BE8C),
      yellow: Color(0xFFEBCB8B),
      blue: Color(0xFF81A1C1),
      magenta: Color(0xFFB48EAD),
      cyan: Color(0xFF88C0D0),
      white: Color(0xFFE5E9F0),
      brightBlack: Color(0xFF4C566A),
      brightRed: Color(0xFFBF616A),
      brightGreen: Color(0xFFA3BE8C),
      brightYellow: Color(0xFFEBCB8B),
      brightBlue: Color(0xFF81A1C1),
      brightMagenta: Color(0xFFB48EAD),
      brightCyan: Color(0xFF8FBCBB),
      brightWhite: Color(0xFFECEFF4),
      searchHitBackground: Color(0xFFEBCB8B),
      searchHitBackgroundCurrent: Color(0xFF88C0D0),
      searchHitForeground: Color(0xFF1E222B),
    ),
    AppPalette.gruvbox => const TerminalTheme(
      cursor: Color(0xFFEBDBB2),
      selection: Color(0x66504945),
      foreground: Color(0xFFEBDBB2),
      background: Color(0xFF1A1B1B),
      black: Color(0xFF282828),
      red: Color(0xFFCC241D),
      green: Color(0xFF98971A),
      yellow: Color(0xFFD79921),
      blue: Color(0xFF458588),
      magenta: Color(0xFFB16286),
      cyan: Color(0xFF689D6A),
      white: Color(0xFFA89984),
      brightBlack: Color(0xFF928374),
      brightRed: Color(0xFFFB4934),
      brightGreen: Color(0xFFB8BB26),
      brightYellow: Color(0xFFFABD2F),
      brightBlue: Color(0xFF83A598),
      brightMagenta: Color(0xFFD3869B),
      brightCyan: Color(0xFF8EC07C),
      brightWhite: Color(0xFFEBDBB2),
      searchHitBackground: Color(0xFFD79921),
      searchHitBackgroundCurrent: Color(0xFF98971A),
      searchHitForeground: Color(0xFF1A1B1B),
    ),
    AppPalette.solarized => const TerminalTheme(
      cursor: Color(0xFF93A1A1),
      selection: Color(0x66586E75),
      foreground: Color(0xFFEEE8D5),
      background: Color(0xFF002731),
      black: Color(0xFF073642),
      red: Color(0xFFDC322F),
      green: Color(0xFF859900),
      yellow: Color(0xFFB58900),
      blue: Color(0xFF268BD2),
      magenta: Color(0xFFD33682),
      cyan: Color(0xFF2AA198),
      white: Color(0xFFEEE8D5),
      brightBlack: Color(0xFF586E75),
      brightRed: Color(0xFFCB4B16),
      brightGreen: Color(0xFF586E75),
      brightYellow: Color(0xFF657B83),
      brightBlue: Color(0xFF839496),
      brightMagenta: Color(0xFF6C71C4),
      brightCyan: Color(0xFF93A1A1),
      brightWhite: Color(0xFFFDF6E3),
      searchHitBackground: Color(0xFFB58900),
      searchHitBackgroundCurrent: Color(0xFF268BD2),
      searchHitForeground: Color(0xFF002731),
    ),
    AppPalette.oneDark => const TerminalTheme(
      cursor: Color(0xFFABB2BF),
      selection: Color(0x665C6370),
      foreground: Color(0xFFABB2BF),
      background: Color(0xFF181A20),
      black: Color(0xFF282C34),
      red: Color(0xFFE06C75),
      green: Color(0xFF98C379),
      yellow: Color(0xFFE5C07B),
      blue: Color(0xFF61AFEF),
      magenta: Color(0xFFC678DD),
      cyan: Color(0xFF56B6C2),
      white: Color(0xFFABB2BF),
      brightBlack: Color(0xFF5C6370),
      brightRed: Color(0xFFE06C75),
      brightGreen: Color(0xFF98C379),
      brightYellow: Color(0xFFE5C07B),
      brightBlue: Color(0xFF61AFEF),
      brightMagenta: Color(0xFFC678DD),
      brightCyan: Color(0xFF56B6C2),
      brightWhite: Color(0xFFC8CCD4),
      searchHitBackground: Color(0xFFE5C07B),
      searchHitBackgroundCurrent: Color(0xFF61AFEF),
      searchHitForeground: Color(0xFF181A20),
    ),
    AppPalette.rosePine => const TerminalTheme(
      cursor: Color(0xFFE0DEF4),
      selection: Color(0x66524F67),
      foreground: Color(0xFFE0DEF4),
      background: Color(0xFF191724),
      black: Color(0xFF26233A),
      red: Color(0xFFEB6F92),
      green: Color(0xFF9CCFD8),
      yellow: Color(0xFFF6C177),
      blue: Color(0xFF31748F),
      magenta: Color(0xFFC4A7E7),
      cyan: Color(0xFFEBBCBA),
      white: Color(0xFFE0DEF4),
      brightBlack: Color(0xFF6E6A86),
      brightRed: Color(0xFFEB6F92),
      brightGreen: Color(0xFF9CCFD8),
      brightYellow: Color(0xFFF6C177),
      brightBlue: Color(0xFF31748F),
      brightMagenta: Color(0xFFC4A7E7),
      brightCyan: Color(0xFFEBBCBA),
      brightWhite: Color(0xFFE0DEF4),
      searchHitBackground: Color(0xFFF6C177),
      searchHitBackgroundCurrent: Color(0xFFC4A7E7),
      searchHitForeground: Color(0xFF191724),
    ),
    AppPalette.everforest => const TerminalTheme(
      cursor: Color(0xFFD3C6AA),
      selection: Color(0x66543A48),
      foreground: Color(0xFFD3C6AA),
      background: Color(0xFF1E2326),
      black: Color(0xFF272E33),
      red: Color(0xFFE67E80),
      green: Color(0xFFA7C080),
      yellow: Color(0xFFDBBC7F),
      blue: Color(0xFF7FBBB3),
      magenta: Color(0xFFD699B6),
      cyan: Color(0xFF83C092),
      white: Color(0xFFD3C6AA),
      brightBlack: Color(0xFF859289),
      brightRed: Color(0xFFE67E80),
      brightGreen: Color(0xFFA7C080),
      brightYellow: Color(0xFFDBBC7F),
      brightBlue: Color(0xFF7FBBB3),
      brightMagenta: Color(0xFFD699B6),
      brightCyan: Color(0xFF83C092),
      brightWhite: Color(0xFFD3C6AA),
      searchHitBackground: Color(0xFFDBBC7F),
      searchHitBackgroundCurrent: Color(0xFFA7C080),
      searchHitForeground: Color(0xFF1E2326),
    ),
    AppPalette.monokai => const TerminalTheme(
      cursor: Color(0xFFF8F8F2),
      selection: Color(0x6649435C),
      foreground: Color(0xFFF8F8F2),
      background: Color(0xFF1B1C1A),
      black: Color(0xFF272822),
      red: Color(0xFFF92672),
      green: Color(0xFFA6E22E),
      yellow: Color(0xFFE6DB74),
      blue: Color(0xFF66D9EF),
      magenta: Color(0xFFAE81FF),
      cyan: Color(0xFFA1EFE4),
      white: Color(0xFFF8F8F2),
      brightBlack: Color(0xFF75715E),
      brightRed: Color(0xFFF92672),
      brightGreen: Color(0xFFA6E22E),
      brightYellow: Color(0xFFE6DB74),
      brightBlue: Color(0xFF66D9EF),
      brightMagenta: Color(0xFFAE81FF),
      brightCyan: Color(0xFFA1EFE4),
      brightWhite: Color(0xFFFFFFFF),
      searchHitBackground: Color(0xFFE6DB74),
      searchHitBackgroundCurrent: Color(0xFFA6E22E),
      searchHitForeground: Color(0xFF1B1C1A),
    ),
    AppPalette.ayuDark => const TerminalTheme(
      cursor: Color(0xFFE6B673),
      selection: Color(0x66409FFF),
      foreground: Color(0xFFB3B1AD),
      background: Color(0xFF0B0E14),
      black: Color(0xFF01060E),
      red: Color(0xFFFF3333),
      green: Color(0xFFC2D94C),
      yellow: Color(0xFFFFB454),
      blue: Color(0xFF59C2FF),
      magenta: Color(0xFFFF8F40),
      cyan: Color(0xFF95E6CB),
      white: Color(0xFFB3B1AD),
      brightBlack: Color(0xFF5C6773),
      brightRed: Color(0xFFFF3333),
      brightGreen: Color(0xFFC2D94C),
      brightYellow: Color(0xFFFFB454),
      brightBlue: Color(0xFF59C2FF),
      brightMagenta: Color(0xFFFF8F40),
      brightCyan: Color(0xFF95E6CB),
      brightWhite: Color(0xFFE6E1CF),
      searchHitBackground: Color(0xFFFFB454),
      searchHitBackgroundCurrent: Color(0xFF59C2FF),
      searchHitForeground: Color(0xFF0B0E14),
    ),
    AppPalette.kanagawa => const TerminalTheme(
      cursor: Color(0xFFDCD7BA),
      selection: Color(0x6654546D),
      foreground: Color(0xFFDCD7BA),
      background: Color(0xFF16161D),
      black: Color(0xFF1F1F28),
      red: Color(0xFFC34043),
      green: Color(0xFF76946A),
      yellow: Color(0xFFC0A36E),
      blue: Color(0xFF7E9CD8),
      magenta: Color(0xFF957FB8),
      cyan: Color(0xFF6A9589),
      white: Color(0xFFC8C093),
      brightBlack: Color(0xFF727169),
      brightRed: Color(0xFFE82424),
      brightGreen: Color(0xFF98BB6C),
      brightYellow: Color(0xFFE6C384),
      brightBlue: Color(0xFF7FB4CA),
      brightMagenta: Color(0xFF938AA9),
      brightCyan: Color(0xFF7AA89F),
      brightWhite: Color(0xFFDCD7BA),
      searchHitBackground: Color(0xFFE6C384),
      searchHitBackgroundCurrent: Color(0xFF7E9CD8),
      searchHitForeground: Color(0xFF16161D),
    ),
    AppPalette.nightOwl => const TerminalTheme(
      cursor: Color(0xFF80A4C2),
      selection: Color(0x664B6479),
      foreground: Color(0xFFD6DEEB),
      background: Color(0xFF011627),
      black: Color(0xFF011627),
      red: Color(0xFFEF5350),
      green: Color(0xFF22DA6E),
      yellow: Color(0xFFFFEB95),
      blue: Color(0xFF82AAFF),
      magenta: Color(0xFFC792EA),
      cyan: Color(0xFF21C7A8),
      white: Color(0xFFD6DEEB),
      brightBlack: Color(0xFF575656),
      brightRed: Color(0xFFEF5350),
      brightGreen: Color(0xFF22DA6E),
      brightYellow: Color(0xFFFFEB95),
      brightBlue: Color(0xFF82AAFF),
      brightMagenta: Color(0xFFC792EA),
      brightCyan: Color(0xFF7FDBCA),
      brightWhite: Color(0xFFFFFFFF),
      searchHitBackground: Color(0xFFFFEB95),
      searchHitBackgroundCurrent: Color(0xFF82AAFF),
      searchHitForeground: Color(0xFF011627),
    ),
    AppPalette.palenight => const TerminalTheme(
      cursor: Color(0xFFFFCC00),
      selection: Color(0x66444A73),
      foreground: Color(0xFFA6ACCD),
      background: Color(0xFF202331),
      black: Color(0xFF292D3E),
      red: Color(0xFFF07178),
      green: Color(0xFFC3E88D),
      yellow: Color(0xFFFFCB6B),
      blue: Color(0xFF82AAFF),
      magenta: Color(0xFFC792EA),
      cyan: Color(0xFF89DDFF),
      white: Color(0xFFA6ACCD),
      brightBlack: Color(0xFF676E95),
      brightRed: Color(0xFFFF8B92),
      brightGreen: Color(0xFFDDFFA7),
      brightYellow: Color(0xFFFFE585),
      brightBlue: Color(0xFF9CC4FF),
      brightMagenta: Color(0xFFE1ACFF),
      brightCyan: Color(0xFFA3F7FF),
      brightWhite: Color(0xFFFFFFFF),
      searchHitBackground: Color(0xFFFFCB6B),
      searchHitBackgroundCurrent: Color(0xFFC792EA),
      searchHitForeground: Color(0xFF202331),
    ),
    AppPalette.synthwave => const TerminalTheme(
      cursor: Color(0xFFFF7EDB),
      selection: Color(0x665A3D8E),
      foreground: Color(0xFFF4F4F7),
      background: Color(0xFF191528),
      black: Color(0xFF241B3D),
      red: Color(0xFFFF5370),
      green: Color(0xFF72F1B8),
      yellow: Color(0xFFFFD866),
      blue: Color(0xFF36F9F6),
      magenta: Color(0xFFFF7EDB),
      cyan: Color(0xFFFEDE5D),
      white: Color(0xFFF4F4F7),
      brightBlack: Color(0xFF8B7EC8),
      brightRed: Color(0xFFFF5370),
      brightGreen: Color(0xFF72F1B8),
      brightYellow: Color(0xFFFFD866),
      brightBlue: Color(0xFF36F9F6),
      brightMagenta: Color(0xFFFF7EDB),
      brightCyan: Color(0xFFFEDE5D),
      brightWhite: Color(0xFFFFFFFF),
      searchHitBackground: Color(0xFFFFD866),
      searchHitBackgroundCurrent: Color(0xFFFF7EDB),
      searchHitForeground: Color(0xFF191528),
    ),
    AppPalette.githubDark => const TerminalTheme(
      cursor: Color(0xFFC9D1D9),
      selection: Color(0x66388BFD),
      foreground: Color(0xFFC9D1D9),
      background: Color(0xFF0D1117),
      black: Color(0xFF161B22),
      red: Color(0xFFFF7B72),
      green: Color(0xFF3FB950),
      yellow: Color(0xFFD29922),
      blue: Color(0xFF58A6FF),
      magenta: Color(0xFFBC8CFF),
      cyan: Color(0xFF39C5CF),
      white: Color(0xFFC9D1D9),
      brightBlack: Color(0xFF6E7681),
      brightRed: Color(0xFFFF7B72),
      brightGreen: Color(0xFF3FB950),
      brightYellow: Color(0xFFD29922),
      brightBlue: Color(0xFF58A6FF),
      brightMagenta: Color(0xFFBC8CFF),
      brightCyan: Color(0xFF39C5CF),
      brightWhite: Color(0xFFFFFFFF),
      searchHitBackground: Color(0xFFD29922),
      searchHitBackgroundCurrent: Color(0xFF58A6FF),
      searchHitForeground: Color(0xFF0D1117),
    ),
  };
}
